// packages/react/src/components/IncremarkBlockquote.tsx
import React from 'react'
import type { Blockquote } from 'mdast'
import { IncremarkRenderer } from './IncremarkRenderer'

export interface IncremarkBlockquoteProps {
  node: Blockquote
}

export const IncremarkBlockquote: React.FC<IncremarkBlockquoteProps> = ({ node }) => {
  return (
    <blockquote className="incremark-blockquote">
      {node.children.map((child, index) => (
        <React.Fragment key={index}>
          <IncremarkRenderer node={child} />
        </React.Fragment>
      ))}
    </blockquote>
  )
}

// packages/svelte/src/components/IncremarkBlockquote.svelte
<!--
  @file IncremarkBlockquote.svelte - 引用组件
  @description 渲染 Markdown 引用块，支持所有块级内容
-->

<script lang="ts">
  import type { Blockquote } from 'mdast'
  import IncremarkRenderer from './IncremarkRenderer.svelte'

  /**
   * 组件 Props
   */
  interface Props {
    /** 引用节点 */
    node: Blockquote
  }

  let { node }: Props = $props()
</script>

<blockquote class="incremark-blockquote">
  {#each node.children as child, index (index)}
    <IncremarkRenderer node={child} />
  {/each}
</blockquote>
