// examples/vue/src/App.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { useIncremark, useDevTools, Incremark, AutoScrollContainer } from '@incremark/vue'
// @ts-ignore
import { math } from 'micromark-extension-math'
// @ts-ignore
import { mathFromMarkdown } from 'mdast-util-math'
import 'katex/dist/katex.min.css'

// 本地 composables 和组件
import { useLocale, useBenchmark } from './composables'
import { BenchmarkPanel, CustomInputPanel, CustomHeading } from './components'

// ============ 国际化 ============
const { locale, t, sampleMarkdown, toggleLocale } = useLocale()

// ============ 打字机配置 ============
const typewriterSpeed = ref(2)
const typewriterInterval = ref(30)
const typewriterRandomStep = ref(true)
const typewriterEffect = ref<'none' | 'fade-in' | 'typing'>('typing')

// ============ 初始化 Incremark（集成打字机） ============
const incremark = useIncremark({
  gfm: true,
  extensions: [math()],
  mdastExtensions: [mathFromMarkdown()],
  // 打字机配置（内部默认使用 defaultPlugins）
  typewriter: {
    enabled: false,
    charsPerTick: [1, Math.max(2, typewriterSpeed.value)],
    tickInterval: typewriterInterval.value,
    effect: typewriterEffect.value,
    cursor: '|'
  }
})

const { markdown, blocks, completedBlocks, pendingBlocks, append, finalize, reset, render, typewriter } = incremark

useDevTools(incremark)

// 监听打字机配置变化
watch([typewriterSpeed, typewriterInterval, typewriterEffect, typewriterRandomStep], () => {
  typewriter.setOptions({
    charsPerTick: typewriterRandomStep.value
      ? [1, Math.max(2, typewriterSpeed.value)] as [number, number]
      : typewriterSpeed.value,
    tickInterval: typewriterInterval.value,
    effect: typewriterEffect.value
  })
})

// ============ 流式输出 ============
const isStreaming = ref(false)

async function simulateStream() {
  reset()
  isStreaming.value = true

  const content = customInputMode.value && customMarkdown.value.trim() 
    ? customMarkdown.value 
    : sampleMarkdown.value
  const chunks = content.match(/[\s\S]{1,20}/g) || []

  for (const chunk of chunks) {
    append(chunk)
    await new Promise((resolve) => setTimeout(resolve, 30))
  }

  finalize()
  isStreaming.value = false
}

function renderOnce() {
  const content = customInputMode.value && customMarkdown.value.trim() 
    ? customMarkdown.value 
    : sampleMarkdown.value
  render(content)
}

// ============ 自动滚动 ============
const autoScrollEnabled = ref(true)
const scrollContainerRef = ref<InstanceType<typeof AutoScrollContainer> | null>(null)

// ============ 自定义输入 ============
const customInputMode = ref(false)
const customMarkdown = ref('')

// ============ Benchmark ============
const { benchmarkMode, benchmarkRunning, benchmarkProgress, benchmarkStats, runBenchmark } = 
  useBenchmark(append, finalize, reset)

function handleRunBenchmark() {
  const content = customInputMode.value && customMarkdown.value.trim() 
    ? customMarkdown.value 
    : sampleMarkdown.value
  runBenchmark(content)
}

// ============ 自定义组件 ============
const useCustomComponents = ref(false)
const customComponents = { heading: CustomHeading }

// 语言切换时重置
watch(locale, () => reset())
</script>

<template>
  <div class="app">
    <header>
      <div class="header-top">
        <h1>{{ t.title }}</h1>
        <button class="lang-toggle" @click="toggleLocale">
          {{ locale === 'zh' ? '🇺🇸 English' : '🇨🇳 中文' }}
        </button>
      </div>
      <div class="controls">
        <button @click="simulateStream" :disabled="isStreaming || benchmarkRunning">
          {{ isStreaming ? t.streaming : t.simulateAI }}
        </button>
        <button @click="renderOnce" :disabled="isStreaming || benchmarkRunning">{{ t.renderOnce }}</button>
        <button @click="reset" :disabled="isStreaming || benchmarkRunning">{{ t.reset }}</button>
        
        <label class="checkbox">
          <input type="checkbox" v-model="useCustomComponents" />
          {{ t.customComponents }}
        </label>
        <label class="checkbox benchmark-toggle">
          <input type="checkbox" v-model="benchmarkMode" />
          {{ t.benchmarkMode }}
        </label>
        <label class="checkbox">
          <input type="checkbox" v-model="customInputMode" />
          {{ t.customInput }}
        </label>
        <label class="checkbox typewriter-toggle">
          <input type="checkbox" v-model="typewriter.enabled.value" />
          {{ t.typewriterMode }}
        </label>
        <label class="checkbox auto-scroll-toggle">
          <input type="checkbox" v-model="autoScrollEnabled" />
          {{ t.autoScroll }}
        </label>
        
        <template v-if="typewriter.enabled.value">
          <label class="speed-control">
            <input type="range" v-model.number="typewriterSpeed" min="1" max="10" step="1" />
            <span class="speed-value">{{ typewriterSpeed }} {{ t.charsPerTick }}</span>
          </label>
          <label class="speed-control">
            <input type="range" v-model.number="typewriterInterval" min="10" max="200" step="10" />
            <span class="speed-value">{{ typewriterInterval }} {{ t.intervalMs }}</span>
          </label>
          <label class="checkbox random-step-toggle">
            <input type="checkbox" v-model="typewriterRandomStep" />
            {{ t.randomStep }}
          </label>
          <select v-model="typewriterEffect" class="effect-select">
            <option value="none">{{ t.effectNone }}</option>
            <option value="fade-in">{{ t.effectFadeIn }}</option>
            <option value="typing">{{ t.effectTyping }}</option>
          </select>
          <button v-if="typewriter.isProcessing.value && !typewriter.isPaused.value" class="pause-btn" @click="typewriter.pause">
            ⏸️ {{ t.pause }}
          </button>
          <button v-if="typewriter.isPaused.value" class="resume-btn" @click="typewriter.resume">
            ▶️ {{ t.resume }}
          </button>
          <button v-if="typewriter.isProcessing.value" class="skip-btn" @click="typewriter.skip">
            ⏭️ {{ t.skip }}
          </button>
        </template>
        
        <span class="stats">
          📝 {{ markdown.length }} {{ t.chars }} |
          ✅ {{ completedBlocks.length }} {{ t.blocks }} |
          ⏳ {{ pendingBlocks.length }} {{ t.pending }}
          <template v-if="typewriter.enabled.value && typewriter.isProcessing.value">
            | ⌨️ {{ typewriter.isPaused.value ? t.paused : t.typing }}
          </template>
        </span>
      </div>
    </header>

    <BenchmarkPanel
      v-if="benchmarkMode"
      :stats="benchmarkStats"
      :running="benchmarkRunning"
      :progress="benchmarkProgress"
      :t="t"
      @run="handleRunBenchmark"
    />

    <CustomInputPanel
      v-if="customInputMode"
      v-model="customMarkdown"
      :t="t"
      @use-example="customMarkdown = sampleMarkdown"
    />

    <main :class="['content', typewriter.enabled.value && `effect-${typewriterEffect}`]">
      <AutoScrollContainer ref="scrollContainerRef" :enabled="autoScrollEnabled" class="scroll-container">
        <Incremark
          :blocks="blocks"
          :components="useCustomComponents ? customComponents : {}"
          :show-block-status="true"
        />
      </AutoScrollContainer>
    </main>
  </div>
</template>

<style>
@import './styles/app.css';
</style>

// examples/react/src/App.tsx
import { useState, useCallback, useMemo, useRef } from 'react'
import { 
  useIncremark, 
  useDevTools, 
  Incremark, 
  AutoScrollContainer, 
  type AutoScrollContainerRef 
} from '@incremark/react'

import { useLocale, useBenchmark } from './hooks'
import { BenchmarkPanel, CustomInputPanel } from './components'
import './index.css'

function App() {
  // ============ 国际化 ============
  const { locale, t, sampleMarkdown, toggleLocale } = useLocale()

  // ============ 打字机配置 ============
  const [typewriterSpeed, setTypewriterSpeed] = useState(2)
  const [typewriterInterval, setTypewriterInterval] = useState(30)
  const [typewriterRandomStep, setTypewriterRandomStep] = useState(true)
  const [typewriterEffect, setTypewriterEffect] = useState<'none' | 'fade-in' | 'typing'>('typing')

  // 计算打字机配置
  const computedCharsPerTick = useMemo(() => {
    return typewriterRandomStep ? [1, Math.max(2, typewriterSpeed)] as [number, number] : typewriterSpeed
  }, [typewriterRandomStep, typewriterSpeed])

  // ============ Incremark（集成打字机） ============
  const incremark = useIncremark({ 
    gfm: true,
    // 打字机配置（内部默认使用 defaultPlugins）
    typewriter: {
      enabled: false,
      charsPerTick: computedCharsPerTick,
      tickInterval: typewriterInterval,
      effect: typewriterEffect,
      cursor: '|'
    }
  })
  const { markdown, blocks, completedBlocks, pendingBlocks, append, finalize, reset, render, typewriter } = incremark

  useDevTools(incremark)

  // 监听打字机配置变化
  useMemo(() => {
    typewriter.setOptions({
      charsPerTick: computedCharsPerTick,
      tickInterval: typewriterInterval,
      effect: typewriterEffect
    })
  }, [computedCharsPerTick, typewriterInterval, typewriterEffect, typewriter])

  // ============ 状态 ============
  const [isStreaming, setIsStreaming] = useState(false)
  const [autoScrollEnabled, setAutoScrollEnabled] = useState(true)
  const scrollContainerRef = useRef<AutoScrollContainerRef>(null)
  const [customInputMode, setCustomInputMode] = useState(false)
  const [customMarkdown, setCustomMarkdown] = useState('')

  const currentMarkdown = useMemo(() => 
    customInputMode && customMarkdown.trim() ? customMarkdown : sampleMarkdown,
    [customInputMode, customMarkdown, sampleMarkdown]
  )

  // ============ Benchmark ============
  const { 
    benchmarkMode, 
    setBenchmarkMode, 
    benchmarkRunning, 
    benchmarkProgress, 
    benchmarkStats, 
    runBenchmark 
  } = useBenchmark(append, finalize, reset)

  const handleRunBenchmark = useCallback(() => {
    runBenchmark(currentMarkdown)
  }, [runBenchmark, currentMarkdown])

  // ============ 流式输出 ============
  const simulateStream = useCallback(async () => {
    reset()
    setIsStreaming(true)

    const chunks = currentMarkdown.match(/[\s\S]{1,30}/g) || []

    for (const chunk of chunks) {
      append(chunk)
      await new Promise((r) => setTimeout(r, 30 + Math.random() * 50))
    }

    finalize()
    setIsStreaming(false)
  }, [append, finalize, reset, currentMarkdown])

  const renderAll = useCallback(() => {
    render(currentMarkdown)
  }, [render, currentMarkdown])

  return (
    <div className="app">
      <header className="header">
        <div className="header-top">
          <h1>{t.title}</h1>
          <button className="lang-toggle" onClick={toggleLocale}>
            {locale === 'zh' ? '🇺🇸 English' : '🇨🇳 中文'}
          </button>
        </div>
        <div className="controls">
          <button className="primary" onClick={simulateStream} disabled={isStreaming || benchmarkRunning}>
            {isStreaming ? t.streaming : t.simulateAI}
          </button>
          <button className="secondary" onClick={renderAll} disabled={isStreaming || benchmarkRunning}>
            {t.renderOnce}
          </button>
          <button className="secondary" onClick={reset} disabled={isStreaming || benchmarkRunning}>
            {t.reset}
          </button>
          
          <label className="checkbox benchmark-toggle">
            <input type="checkbox" checked={benchmarkMode} onChange={(e) => setBenchmarkMode(e.target.checked)} />
            {t.benchmarkMode}
          </label>
          <label className="checkbox">
            <input type="checkbox" checked={customInputMode} onChange={(e) => setCustomInputMode(e.target.checked)} />
            {t.customInput}
          </label>
          <label className="checkbox typewriter-toggle">
            <input type="checkbox" checked={typewriter.enabled} onChange={(e) => typewriter.setEnabled(e.target.checked)} />
            {t.typewriterMode}
          </label>
          <label className="checkbox auto-scroll-toggle">
            <input type="checkbox" checked={autoScrollEnabled} onChange={(e) => setAutoScrollEnabled(e.target.checked)} />
            {t.autoScroll}
          </label>
          
          {typewriter.enabled && (
            <>
              <label className="speed-control">
                <input type="range" value={typewriterSpeed} onChange={(e) => setTypewriterSpeed(Number(e.target.value))} min="1" max="10" step="1" />
                <span className="speed-value">{typewriterSpeed} {t.charsPerTick}</span>
              </label>
              <label className="speed-control">
                <input type="range" value={typewriterInterval} onChange={(e) => setTypewriterInterval(Number(e.target.value))} min="10" max="200" step="10" />
                <span className="speed-value">{typewriterInterval} {t.intervalMs}</span>
              </label>
              <label className="checkbox random-step-toggle">
                <input type="checkbox" checked={typewriterRandomStep} onChange={(e) => setTypewriterRandomStep(e.target.checked)} />
                {t.randomStep}
              </label>
              <select value={typewriterEffect} onChange={(e) => setTypewriterEffect(e.target.value as 'none' | 'fade-in' | 'typing')} className="effect-select">
                <option value="none">{t.effectNone}</option>
                <option value="fade-in">{t.effectFadeIn}</option>
                <option value="typing">{t.effectTyping}</option>
              </select>
              {typewriter.isProcessing && !typewriter.isPaused && (
                <button className="pause-btn" onClick={typewriter.pause}>⏸️ {t.pause}</button>
              )}
              {typewriter.isPaused && (
                <button className="resume-btn" onClick={typewriter.resume}>▶️ {t.resume}</button>
              )}
              {typewriter.isProcessing && (
                <button className="skip-btn" onClick={typewriter.skip}>⏭️ {t.skip}</button>
              )}
            </>
          )}
        </div>
        <div className="stats">
          📝 {markdown.length} {t.chars} |
          ✅ {completedBlocks.length} {t.blocks} |
          ⏳ {pendingBlocks.length} {t.pending}
          {typewriter.enabled && typewriter.isProcessing && ` | ⌨️ ${typewriter.isPaused ? t.paused : t.typing}`}
        </div>
      </header>

      {benchmarkMode && (
        <BenchmarkPanel
          stats={benchmarkStats}
          running={benchmarkRunning}
          progress={benchmarkProgress}
          t={t}
          onRun={handleRunBenchmark}
        />
      )}

      {customInputMode && (
        <CustomInputPanel
          value={customMarkdown}
          onChange={setCustomMarkdown}
          onUseExample={() => setCustomMarkdown(sampleMarkdown)}
          t={t}
        />
      )}

      <main className={`content ${typewriter.enabled ? `effect-${typewriterEffect}` : ''}`}>
        <AutoScrollContainer ref={scrollContainerRef} enabled={autoScrollEnabled} className="scroll-container">
          <Incremark blocks={blocks} showBlockStatus={true} />
        </AutoScrollContainer>
      </main>
    </div>
  )
}

export default App
