// packages/vue/src/components/IncremarkBlockquote.vue
<script setup lang="ts">
import type { Blockquote } from 'mdast'
import IncremarkRenderer from './IncremarkRenderer.vue'

defineProps<{
  node: Blockquote
}>()
</script>

<template>
  <blockquote class="incremark-blockquote">
    <IncremarkRenderer v-for="(child, index) in node.children" :key="index" :node="child" />
  </blockquote>
</template>

// packages/react/src/components/IncremarkBlockquote.tsx
import React from 'react'
import type { Blockquote } from 'mdast'
import { IncremarkRenderer } from './IncremarkRenderer'

export interface IncremarkBlockquoteProps {
  node: Blockquote
}

export const IncremarkBlockquote: React.FC<IncremarkBlockquoteProps> = ({ node }) => {
  return (
    <blockquote className="incremark-blockquote">
      {node.children.map((child, index) => (
        <React.Fragment key={index}>
          <IncremarkRenderer node={child} />
        </React.Fragment>
      ))}
    </blockquote>
  )
}
