// packages/react/src/components/Incremark.tsx
import React from 'react'
import type { ParsedBlock } from '@incremark/core'
import { IncremarkRenderer } from './IncremarkRenderer'
import { IncremarkFootnotes } from './IncremarkFootnotes'
import type { UseIncremarkReturn } from '../hooks/useIncremark'
import { IncremarkContainerProvider } from './IncremarkContainerProvider'

interface BlockWithStableId extends ParsedBlock {
  stableId: string
  isLastPending?: boolean // 是否是最后一个 pending 块
}

/**
 * 代码块配置
 */
export interface CodeBlockConfig {
  /** 是否从一开始就接管渲染，而不是等到 completed 状态 */
  takeOver?: boolean
}

export interface IncremarkProps {
  /** 要渲染的块列表 */
  blocks?: BlockWithStableId[]
  /** 内容是否完全显示完成（用于控制脚注等需要在内容完全显示后才出现的元素）
   * 如果传入了 incremark，则会自动使用 incremark.isDisplayComplete，此 prop 被忽略 */
  isDisplayComplete?: boolean
  /** 自定义组件映射 */
  components?: Partial<Record<string, React.ComponentType<{ node: any }>>>
  /** 自定义容器组件映射，key 为容器名称（如 'warning', 'info'） */
  customContainers?: Record<string, React.ComponentType<{ name: string; options?: Record<string, any>; children?: React.ReactNode }>>
  /** 自定义代码块组件映射，key 为代码语言名称（如 'echart', 'mermaid'） */
  customCodeBlocks?: Record<string, React.ComponentType<{ codeStr: string; lang?: string | undefined; completed?: boolean | undefined; takeOver?: boolean | undefined }>>
  /** 代码块配置映射，key 为代码语言名称 */
  codeBlockConfigs?: Record<string, CodeBlockConfig>
  /** 是否显示块状态（待处理块边框） */
  showBlockStatus?: boolean
  /** 自定义类名 */
  className?: string
  /** 可选：useIncremark 返回的对象（用于自动提供 context） */
  incremark?: UseIncremarkReturn
}

/**
 * Incremark 主渲染组件
 *
 * @example
 * ```tsx
 * import { useIncremark, Incremark } from '@incremark/react'
 *
 * // 推荐用法: 传入 incremark 对象（自动提供 context）
 * function App() {
 *   const incremark = useIncremark()
 *   return <Incremark incremark={incremark} />
 * }
 * ```
 */
export const Incremark: React.FC<IncremarkProps> = (props) => {
  const {
    blocks: propsBlocks,
    isDisplayComplete: propsIsDisplayComplete = false,
    components,
    customContainers,
    customCodeBlocks,
    showBlockStatus = true,
    className = '',
    incremark
  } = props

  // 如果传入了 incremark 对象，自动提供 context
  if (incremark) {
    const { blocks, isDisplayComplete, _definitionsContextValue } = incremark
    return (
      <IncremarkContainerProvider definitions={_definitionsContextValue}>
        <IncremarkInternal
          blocks={blocks}
          components={components}
          customContainers={customContainers}
          customCodeBlocks={customCodeBlocks}
          showBlockStatus={showBlockStatus}
          className={className}
          isDisplayComplete={isDisplayComplete}
        />
      </IncremarkContainerProvider>
    )
  }

  // 否则使用传入的 props
  const blocks = propsBlocks || []
  const isDisplayComplete = propsIsDisplayComplete

  return (
    <IncremarkInternal
      blocks={blocks}
      components={components}
      customContainers={customContainers}
      customCodeBlocks={customCodeBlocks}
      showBlockStatus={showBlockStatus}
      className={className}
      isDisplayComplete={isDisplayComplete}
    />
  )
}

/**
 * 内部渲染组件（不对外暴露）
 */
interface IncremarkInternalProps {
  blocks: BlockWithStableId[]
  components?: Partial<Record<string, React.ComponentType<{ node: any }>>>
  customContainers?: Record<string, React.ComponentType<{ name: string; options?: Record<string, any>; children?: React.ReactNode }>>
  customCodeBlocks?: Record<string, React.ComponentType<{ codeStr: string; lang?: string; completed?: boolean; takeOver?: boolean }>>
  codeBlockConfigs?: Record<string, { takeOver?: boolean }>
  showBlockStatus: boolean
  className: string
  isDisplayComplete: boolean
}

const IncremarkInternal: React.FC<IncremarkInternalProps> = ({
  blocks,
  components,
  customContainers,
  customCodeBlocks,
  codeBlockConfigs,
  showBlockStatus,
  className,
  isDisplayComplete
}) => {
  return (
    <div className={`incremark ${className}`}>
      {/* 主要内容块 */}
      {blocks.map((block) => {
        // 过滤掉 definition 和 footnoteDefinition 节点（它们会在其他地方渲染）
        if (block.node.type === 'definition' || block.node.type === 'footnoteDefinition') {
          return null
        }

        const isPending = block.status === 'pending'
        const classes = [
          'incremark-block',
          isPending ? 'incremark-pending' : 'incremark-completed',
          showBlockStatus && 'incremark-show-status',
          block.isLastPending && 'incremark-last-pending'
        ].filter(Boolean).join(' ')

        return (
          <div key={block.stableId} className={classes}>
            <IncremarkRenderer
              node={block.node}
              components={components}
              customContainers={customContainers}
              customCodeBlocks={customCodeBlocks}
              codeBlockConfigs={codeBlockConfigs}
              blockStatus={block.status}
            />
          </div>
        )
      })}

      {/* 脚注列表（仅在内容完全显示后显示） */}
      {isDisplayComplete && (
        <IncremarkFootnotes />
      )}
    </div>
  )
}

// packages/vue/src/components/Incremark.vue
<script setup lang="ts">
import { computed, type Component } from 'vue'
import type { ParsedBlock, RootContent } from '@incremark/core'
import { useDefinationsContext } from '../composables/useDefinationsContext'
import type { UseIncremarkReturn } from '../composables/useIncremark'
import IncremarkRenderer from './IncremarkRenderer.vue'
import IncremarkFootnotes from './IncremarkFootnotes.vue'

// 组件映射类型
export type ComponentMap = Partial<Record<string, Component>>

// 带稳定 ID 的块类型
export interface BlockWithStableId extends ParsedBlock {
  stableId: string
  isLastPending?: boolean // 是否是最后一个 pending 块
}

/**
 * 代码块配置
 */
export interface CodeBlockConfig {
  /** 是否从一开始就接管渲染，而不是等到 completed 状态 */
  takeOver?: boolean
}

/**
 * 代码块配置
 */
export interface CodeBlockConfig {
  /** 是否从一开始就接管渲染，而不是等到 completed 状态 */
  takeOver?: boolean
}

const props = withDefaults(
  defineProps<{
    /** 要渲染的块列表（来自 useIncremark 的 blocks） */
    blocks?: BlockWithStableId[]
    /** 内容是否完全显示完成（用于控制脚注等需要在内容完全显示后才出现的元素）
     * 如果传入了 incremark，则会自动使用 incremark.isDisplayComplete，此 prop 被忽略 */
    isDisplayComplete?: boolean
    /** 自定义组件映射，key 为节点类型 */
    components?: ComponentMap
    /** 自定义容器组件映射，key 为容器名称（如 'warning', 'info'） */
    customContainers?: Record<string, Component>
    /** 自定义代码块组件映射，key 为代码语言名称（如 'echart', 'mermaid'） */
    customCodeBlocks?: Record<string, Component>
    /** 代码块配置映射，key 为代码语言名称 */
    codeBlockConfigs?: Record<string, CodeBlockConfig>
    /** 待处理块的样式类名 */
    pendingClass?: string
    /** 已完成块的样式类名 */
    completedClass?: string
    /** 是否显示块状态边框 */
    showBlockStatus?: boolean
    /** 可选：useIncremark 返回的对象（用于自动注入数据） */
    incremark?: UseIncremarkReturn
  }>(),
  {
    blocks: () => [],
    isDisplayComplete: false,
    components: () => ({}),
    customContainers: () => ({}),
    customCodeBlocks: () => ({}),
    codeBlockConfigs: () => ({}),
    pendingClass: 'incremark-pending',
    completedClass: 'incremark-completed',
    showBlockStatus: false
  }
)

const {
  footnoteReferenceOrder
} = useDefinationsContext();

// 计算实际使用的 blocks 和 isDisplayComplete
const actualBlocks = computed<BlockWithStableId[]>(() => props.incremark?.blocks.value || props.blocks || [])
const actualIsDisplayComplete = computed(() => {
  // 优先使用 incremark 提供的 isDisplayComplete（已考虑打字机等状态）
  if (props.incremark) {
    return props.incremark.isDisplayComplete.value
  }
  // 否则使用用户传入的 isDisplayComplete
  return props.isDisplayComplete
})

</script>

<template>
  <div class="incremark">
    <!-- 主要内容块 -->
    <template v-for="block in actualBlocks">
      <div
        v-if="block.node.type !== 'definition' && block.node.type !== 'footnoteDefinition'"
        :key="block.stableId"
        :class="[
          'incremark-block',
          block.status === 'completed' ? completedClass : pendingClass,
          { 'incremark-show-status': showBlockStatus },
          { 'incremark-last-pending': block.isLastPending }
        ]"
      >
        <!-- 使用 IncremarkRenderer 统一处理所有节点类型 -->
        <IncremarkRenderer
          :node="block.node"
          :block-status="block.status"
          :custom-containers="customContainers"
          :custom-code-blocks="customCodeBlocks"
          :code-block-configs="codeBlockConfigs"
          :components="components"
        />
      </div>
    </template>

    <!-- 脚注列表（仅在内容完全显示后显示） -->
    <IncremarkFootnotes
      v-if="actualIsDisplayComplete && footnoteReferenceOrder.length > 0"
    />
  </div>
</template>
