// packages/svelte/src/components/IncremarkFootnotes.svelte
<!--
  @file IncremarkFootnotes.svelte - 脚注列表组件
  @description 在文档底部渲染所有脚注定义，按引用出现的顺序排列
-->

<script lang="ts">
  import type { Readable } from 'svelte/store'
  import type { FootnoteDefinition, RootContent } from 'mdast'
  import { getDefinitionsContext } from '../context/definitionsContext'
  import IncremarkRenderer from './IncremarkRenderer.svelte'

  // 从 context 获取数据
  let definations: Readable<Record<string, any>> | null = null
  let footnoteDefinitions: Readable<Record<string, FootnoteDefinition>> | null = null
  let footnoteReferenceOrder: Readable<string[]> | null = null

  try {
    const context = getDefinitionsContext()
    definations = context.definations
    footnoteDefinitions = context.footnoteDefinitions
    footnoteReferenceOrder = context.footnoteReferenceOrder
  } catch {
    // Context 不存在
  }

  /**
   * 按引用顺序排列的脚注列表
   * 只显示已有定义的脚注
   */
  const orderedFootnotes = $derived.by(() => {
    if (!footnoteReferenceOrder || !footnoteDefinitions) {
      return []
    }
    const order = $footnoteReferenceOrder
    const definitions = $footnoteDefinitions
    return order
      .map(identifier => ({
        identifier,
        definition: definitions[identifier]
      }))
      .filter(item => item.definition !== undefined)
  })

  /**
   * 是否有脚注需要显示
   */
  const hasFootnotes = $derived(orderedFootnotes.length > 0)
</script>

{#if hasFootnotes}
  <section class="incremark-footnotes">
    <hr class="incremark-footnotes-divider" />
    <ol class="incremark-footnotes-list">
      {#each orderedFootnotes as item, index (item.identifier)}
        <li
          id="fn-{item.identifier}"
          class="incremark-footnote-item"
        >
          <div class="incremark-footnote-content">
            <!-- 脚注序号 -->
            <span class="incremark-footnote-number">{index + 1}.</span>
            
            <!-- 脚注内容 -->
            <div class="incremark-footnote-body">
              {#each item.definition.children as child, childIndex (childIndex)}
                <IncremarkRenderer node={child as RootContent} />
              {/each}
            </div>
          </div>
          
          <!-- 返回链接 -->
          <a 
            href="#fnref-{item.identifier}" 
            class="incremark-footnote-backref"
            aria-label="返回引用位置"
          >
            ↩
          </a>
        </li>
      {/each}
    </ol>
  </section>
{/if}

// packages/vue/src/components/IncremarkFootnotes.vue
<!--
/**
 * 脚注列表组件
 *
 * 在文档底部渲染所有脚注定义，按引用出现的顺序排列
 *
 * @component IncremarkFootnotes
 *
 * @remarks
 * 样式定义在 @incremark/theme 中的 footnotes.less
 * footnoteReferenceOrder 自动从 context 获取，无需手动传递
 */
-->
<script setup lang="ts">
import { computed } from 'vue'
import type { FootnoteDefinition, RootContent } from 'mdast'
import { useDefinationsContext } from '../composables/useDefinationsContext'
import IncremarkRenderer from './IncremarkRenderer.vue'

const { definations, footnoteDefinitions, footnoteReferenceOrder } = useDefinationsContext()

/**
 * 按引用顺序排列的脚注列表
 * 只显示已有定义的脚注
 */
const orderedFootnotes = computed<Array<{ identifier: string; definition: FootnoteDefinition }>>(() => {
  return footnoteReferenceOrder.value
    .map(identifier => ({
      identifier,
      definition: footnoteDefinitions.value[identifier]
    }))
    .filter(item => item.definition !== undefined)
})

/**
 * 是否有脚注需要显示
 */
const hasFootnotes = computed(() => orderedFootnotes.value.length > 0)
</script>

<template>
  <section v-if="hasFootnotes" class="incremark-footnotes">
    <hr class="incremark-footnotes-divider" />
    <ol class="incremark-footnotes-list">
      <li
        v-for="(item, index) in orderedFootnotes"
        :key="item.identifier"
        :id="`fn-${item.identifier}`"
        class="incremark-footnote-item"
      >
        <div class="incremark-footnote-content">
          <!-- 脚注序号 -->
          <span class="incremark-footnote-number">{{ index + 1 }}.</span>
          
          <!-- 脚注内容 -->
          <div class="incremark-footnote-body">
            <IncremarkRenderer
              v-for="(child, childIndex) in item.definition.children"
              :key="childIndex"
              :node="(child as RootContent)"
            />
          </div>
        </div>
        
        <!-- 返回链接 -->
        <a 
          :href="`#fnref-${item.identifier}`" 
          class="incremark-footnote-backref"
          aria-label="返回引用位置"
        >
          ↩
        </a>
      </li>
    </ol>
  </section>
</template>
